let imageData = [
    {id: 0, name:`BBQ Jerk Wings`, fileName:`bbq_jerk_wings.jpg`},
    {id: 1, name:`Beef Patties`, fileName:`beef_patty.jpg`},
    {id: 2, name:`Beverages`, fileName:`beverages.jpg`},
    {id: 3, name:`Brown Stew Chicken`, fileName:`brown_stew_chicken.jpg`},
    {id: 4, name:`Chicken Soup`, fileName:`chicken_soup.jpg`},
    {id: 5, name:`Cow Foot`, fileName:`cow_foot.jpg`},
    {id: 6, name:`Curry Chicken`, fileName:`curry_chicken.jpg`},
    {id: 7, name:`Curry Chicken`, fileName:`curry_chicken2.jpg`},
    {id: 8, name:`Curry Goat`, fileName:`curry_goat.jpg`},
    {id: 9, name:`Curry Goat`, fileName:`curry_goat_2.jpg`},
    {id: 10, name:`Curry Goat`, fileName:`curry_goat_3.jpg`},
    {id: 11, name:`Food and Drinks`, fileName:`food1.jpg`},
    {id: 12, name:`special`, fileName:`food2.jpg`},
    {id: 13, name:`Jerk Chicken`, fileName:`jerk_chicken.jpg`},
    {id: 14, name:`Jerk Wings`, fileName:`jerk_wings.jpg`},
    {id: 15, name:`Oxtails`, fileName:`oxtails.jpg`},
    {id: 16, name:`Pasta_salad`, fileName:`pasta_salad.jpg`},
    {id: 17, name:`Peanut Punch`, fileName:`peanut_punch.jpg`},
    {id: 18, name:`plate1`, fileName:`plate1.jpg`},
    {id: 19, name:`plate2`, fileName:`plate2.jpg`},
    {id: 20, name:`plate3`, fileName:`plate3.jpg`},
    {id: 21, name:`plate4`, fileName:`plate4.jpg`},
    {id: 22, name:`plate5`, fileName:`plate5.jpg`},
    {id: 23, name:`Shrimp and Pasta`, fileName:`plate6.jpg`},
    {id: 24, name:`plate7`, fileName:`plate7.jpg`},
    {id: 25, name:`Jerk Chick with Rice, Peas and Cabbage`, fileName:`plate8.jpg`},
    {id: 26, name:`Red Peas Soup`, fileName:`red_peas_soup.jpg`},
    {id: 27, name:`Rice and Peas`, fileName:`rice_and_peas.jpg`},
    {id: 28, name:`Rice`, fileName:`rice.jpg`},
    {id: 29, name:`Sausage and Pasta`, fileName:`sausage_pasta.jpg`},
    {id: 30, name:`Stew Chicken`, fileName:`stew_chicken.jpg`},
    {id: 31, name:`Stew Peas`, fileName:`stew_peas.jpg`},
    {id: 32, name:`The Tropic Salad`, fileName:`the_tropics_salad.jpg`},
    {id: 33, name:`Vegetarian`, fileName:`vegetarian.jpg`},
    {id: 34, name:`White Rice`, fileName:`white_rice.jpg`},
    {id: 35, name:`Yellow Rice`, fileName:`yellow_rice.jpg`},
]
export default imageData